apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

managedNodeGroups:
  - name: roboshop
    instanceTypes: ["t3.small"]
    desiredCapacity: 3
    minSize: 3
    maxSize: 10
    spot: false
    # instanceTypes: ["t3.small", "t3.small","t3.small","t3.small"] # we can use instanceTypes: ["t3.small"]
    # desiredCapacity: 3   # instanceTypes: ["t3.small", "t3.medium"] Multi-instance types (best practice)
    # minSize ≤ desiredCapacity ≤ maxSize
#instanceTypes: ["m7i-flex.large", "m7i-flex.large","m7i-flex.large","m7i-flex.large"]    
#t3.small
#["m5.large", "c5.large","c5.large","c5.large"]
#m7i-flex.large

#     apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: roboshop
#   region: us-east-1

# managedNodeGroups:
#   - name: roboshop
#     instanceType: t3.medium
#     desiredCapacity: 2
#     spot: false